apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metal-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.122.50-192.168.122.100

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - metal-pool